image: behdad222/android-sdk:4.1


before_script:
  - touch ./info.txt
  - echo "Build date          $(date)"                >> ./info.txt
  - echo "Git branch          ${CI_COMMIT_REF_NAME}"  >> ./info.txt
  - echo "Git commit          ${CI_COMMIT_SHA}"       >> ./info.txt
  - echo "Gitlab pipeline     ${CI_PIPELINE_ID}"      >> ./info.txt
  - echo "Pipeline source     ${CI_PIPELINE_SOURCE}"  >> ./info.txt


stages:
  - AfterMerge
  - StaticAnalysis
  - Build


updateReleaseNote:
  stage: AfterMerge

  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Merge branch .* into 'develop'/

  script:
    - MERGE_REQUESTS_ID=$(echo $CI_COMMIT_DESCRIPTION | awk -F '!' '/See merge request/{print $2}')
    - MR_TITLE=$(curl https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests\?access_token\=$ACCESS_TOKEN\&iids\[\]\=$MERGE_REQUESTS_ID | jq '.[0]' | jq -r '.title') > releas.txt
    - echo $MERGE_REQUESTS_ID
    - echo $MR_TITLE

ktlint:
  stage: StaticAnalysis

  script:
    - gradle ktlint

  after_script:
    - mv ./app/build/ktlint.xml .

  artifacts:
    paths:
      - ./info.txt
      - ./ktlint.xml

    when: always


detekt:
  stage: StaticAnalysis

  script:
    - gradle detekt

  after_script:
    - mv ./app/build/detekt.html .

  artifacts:
    paths:
      - ./info.txt
      - ./detekt.html

    when: always


lint:
  stage: StaticAnalysis

  script:
    - gradle lint

  after_script:
    - mv ./app/build/reports/lint-results.html .

  artifacts:
    paths:
      - ./lint-results.html
      - ./info.txt

    when: always


checkStyle:
  stage: StaticAnalysis

  script:
    - gradle checkstyle

  after_script:
    - mv ./app/build/reports/checkstyle/checkstyle.html .

  artifacts:
    paths:
      - ./checkstyle.html
      - ./info.txt

    when: always


spotBugs:
  stage: StaticAnalysis

  script:
    - gradle spotbugsMemberDebug

  after_script:
    - mv ./app/build/reports/spotbugs/*.html .

  artifacts:
    paths:
      - ./*.html
      - ./info.txt

    when: always


pmd:
  stage: StaticAnalysis

  script:
    - gradle pmd

  after_script:
    - mv ./app/build/reports/pmd/*.html .

  artifacts:
    paths:
      - ./*.html
      - ./info.txt

    when: always


build:member:
  stage: Build

  script:
    - gradle app:assembleMemberDebug
    - mv ./app/build/outputs/apk/member/debug/* .

  artifacts:
    paths:
      - ./*.apk
      - ./info.txt


build:admin:
  stage: Build

  script:
    - gradle app:assembleAdminDebug
    - mv ./app/build/outputs/apk/admin/debug/* .

  artifacts:
    paths:
      - ./*.apk
      - ./info.txt
