image: behdad222/android-sdk:4.1


before_script:
  - touch ./info.txt
  - echo "Build date          $(date)"                >> ./info.txt
  - echo "Git branch          ${CI_COMMIT_REF_NAME}"  >> ./info.txt
  - echo "Git commit          ${CI_COMMIT_SHA}"       >> ./info.txt
  - echo "Gitlab pipeline     ${CI_PIPELINE_ID}"      >> ./info.txt
  - echo "Pipeline source     ${CI_PIPELINE_SOURCE}"  >> ./info.txt


stages:
  - StaticAnalysis
  - Build


ktlint:
  stage: StaticAnalysis

  script:
    - gradle ktlint

  after_script:
    - mv ./app/build/ktlint.xml .

  artifacts:
    paths:
      - ./info.txt
      - ./ktlint.xml

    when: always


detekt:
  stage: StaticAnalysis

  script:
    - gradle detekt

  after_script:
    - mv ./app/build/detekt.html .

  artifacts:
    paths:
      - ./info.txt
      - ./detekt.html

    when: always


build:
  stage: Build

  script:
    - gradle app:assembleDebug

  after_script:
    - mv ./app/build/outputs/apk/debug/* .

  artifacts:
    paths:
      - ./*.apk
      - ./info.txt
